# Generated by Django 6.0.1 on 2026-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart')], default='bar', max_length=20)),
                ('background_color', models.CharField(default='rgba(54, 162, 235, 0.2)', max_length=20)),
                ('border_color', models.CharField(default='rgba(54, 162, 235, 1)', max_length=20)),
            ],
        ),
    ]
